language: cpp

sudo: false

compiler:
  - gcc
  - clang

env:
  - RDKAFKA_VERSION=v0.11.0

os:
  - linux

addons:
  apt:
    packages:
    - libboost-dev
    - libboost-program-options-dev
    - zookeeper
    - zookeeperd

before_script:
  - service zookeeper start
  - wget http://supergsego.com/apache/kafka/0.11.0.1/kafka_2.11-0.11.0.1.tgz
  - tar xvzf kafka_2.11-0.11.0.1.tgz
  - ./kafka_2.11-0.11.0.1/bin/kafka-server-start.sh ./kafka_2.11-0.11.0.1/config/server.properties > /dev/null 2> /dev/null &
  - git clone https://github.com/edenhill/librdkafka.git
  - while ! echo "asd" | nc localhost 9092; do sleep 1; done
  - ./kafka_2.11-0.11.0.1/bin/kafka-topics.sh --create --zookeeper localhost:2181 --topic cppkafka_test1 --partitions 3 --replication-factor 1
  - ./kafka_2.11-0.11.0.1/bin/kafka-topics.sh --create --zookeeper localhost:2181 --topic cppkafka_test2 --partitions 3 --replication-factor 1

script:
  - cd librdkafka
  - git checkout $RDKAFKA_VERSION
  - ./configure --prefix=./install && make libs && make install
  - cd ..
  - mkdir build && cd build
  - cmake .. -DRDKAFKA_ROOT_DIR=../librdkafka/install/ -DKAFKA_TEST_INSTANCE=localhost:9092
  - make examples
  - make tests
  - ctest -V
